version: '3'
vars:
  BUILD_DIR: build
tasks:
  setup:
    - |-
      cmake -B {{.BUILD_DIR}} -G Ninja \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_CXX_COMPILER=/opt/homebrew/opt/llvm/bin/clang++ \
        -DCMAKE_C_COMPILER=/opt/homebrew/opt/llvm/bin/clang

  build:
    deps: [setup]
    cmds:
      - cmake --build {{.BUILD_DIR}} -j $(nproc)

  clean: rm -rf {{.BUILD_DIR}}
